#!/usr/bin/python3
# coding : utf-8
# @Time  : 2021/3/30 16:02
# @File  : test_browser_wexin.py
# __author__ = 'yangyanqin'
# Generated by Selenium IDE

"""web 自动化测试"""

import shelve
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options


class TestTest():
    def setup_method(self, method):
        # 浏览器的复用：
        # 1. 需要配置环境变量，把浏览器可执行文件的路径配置到环境变量中
        # 2. dos 下输入：chrome --remote-debugging-port=9966
        # 3. 脚本中需要设置 Options 和 debugger_address
        option = Options()
        option.debugger_address = "127.0.0.1:9966"
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(4)

    def teardown_method(self, method):
        # self.driver.quit()
        pass

    def test_test(self):
        self.driver.get("https://www.baidu.com")
        self.driver.find_element(By.ID, "kw").send_keys("霍格沃兹测试学院")
        time.sleep(4)
        self.driver.find_element(By.ID, "su").click()
        self.driver.find_element(By.LINK_TEXT, "霍格沃兹测试学院 – 测试开发工程师的黄埔军校").click()
        time.sleep(4)

    def test_wework_cookies(self):
        """通过获取cookie，去掉过去时间参数，然后再添加到浏览器"""
        time.sleep(4)
        self.driver.get("https://work.weixin.qq.com/")
        # cookies = list(self.driver.get_cookies())  # 获取 cookies
        cookies = [
            {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wwrtx.vid', 'path': '/', 'secure': False,
             'value': '1688850145931141'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.vst', 'path': '/', 'secure': False,
             'value': 'Jz6GEJhD5SlaZqtLjd2ypbN9KElFFPgg_xI3lcM_g_I1vOK7W_JeyZgSRtOCa3S7A4IIB1lzs4mis5l60y5Q2JbpV-BFTZjWr9XoLBah0UknkcZauXhROM7sEuNX6Pf97gd6xjCi18y90YGFatIBJ32IbZ_9NsrLCAhHG39Wn7bJ3ruyDsxt3DgMsAtHXpDx8D90D0qvmOpShsq57oQJtMO1Qrr0VaLFEvsnMkTScr3-Tmmb55GnsFptnDgwaJsgwGS07hVcob1lXVLf9q2UrQ'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wxpay.vid', 'path': '/', 'secure': False,
             'value': '1688850145931141'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wxpay.corpid', 'path': '/', 'secure': False,
             'value': '1970324963443594'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wwrtx.d2st', 'path': '/', 'secure': False,
             'value': 'a5538072'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.sid', 'path': '/', 'secure': False,
             'value': 'RTyw3gv73HNeWu1vNC8I_OewH8D9pNVER2emOPj91OKiHY3mZx8y0oAre6fDSIZy'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.ltype', 'path': '/', 'secure': False,
             'value': '1'}, {'domain': '.work.weixin.qq.com', 'expiry': 1648690020, 'httpOnly': False,
                             'name': 'Hm_lvt_9364e629af24cb52acc78b43e8c9f77d', 'path': '/', 'secure': False,
                             'value': '1617086828,1617093726,1617097791,1617154020'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.ref', 'path': '/', 'secure': False,
             'value': 'direct'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'Hm_lpvt_9364e629af24cb52acc78b43e8c9f77d',
             'path': '/', 'secure': False, 'value': '1617154020'},
            {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.refid', 'path': '/', 'secure': False,
             'value': '26611713121620184'},
            {'domain': '.qq.com', 'expiry': 1617240433, 'httpOnly': False, 'name': '_gid', 'path': '/', 'secure': False,
             'value': 'GA1.2.729688091.1617086828'},
            {'domain': 'work.weixin.qq.com', 'expiry': 1617185050, 'httpOnly': True, 'name': 'ww_rtkey', 'path': '/',
             'secure': False, 'value': '56kmueb'},
            {'domain': '.qq.com', 'expiry': 1680226033, 'httpOnly': False, 'name': '_ga', 'path': '/', 'secure': False,
             'value': 'GA1.2.1805803985.1617086828'},
            {'domain': '.work.weixin.qq.com', 'expiry': 1648622815, 'httpOnly': False, 'name': 'wwrtx.c_gdpr',
             'path': '/', 'secure': False, 'value': '0'},
            {'domain': '.work.weixin.qq.com', 'expiry': 1619746036, 'httpOnly': False, 'name': 'wwrtx.i18n_lan',
             'path': '/', 'secure': False, 'value': 'cht'}]
        for cookie in cookies:
            if "expiry" in cookie.keys():
                cookie.pop("expiry")
                # 把去掉过期时间的cookies添加到driver中，这样方便 driver 的使用
            self.driver.add_cookie(cookie)

        self.driver.get("https://work.weixin.qq.com/wework_admin/frame")
        self.driver.find_element(By.ID, "menu_contacts").click()

    def test_wework_storage_cookies(self):
        """先获取cookies,然后把获取到的cookies 存储到本地"""
        self.driver.get("https://work.weixin.qq.com/")
        db = shelve.open("cookies")  # 打开一个数据库,python 自带，本地会创建三个文件
        # cookies 的存储
        # cookies = [
        #     {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wwrtx.vid', 'path': '/', 'secure': False,
        #      'value': '1688850145931141'},
        #     {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.vst', 'path': '/', 'secure': False,
        #      'value': 'Jz6GEJhD5SlaZqtLjd2ypbN9KElFFPgg_xI3lcM_g_I1vOK7W_JeyZgSRtOCa3S7A4IIB1lzs4mis5l60y5Q2JbpV-BFTZjWr9XoLBah0UknkcZauXhROM7sEuNX6Pf97gd6xjCi18y90YGFatIBJ32IbZ_9NsrLCAhHG39Wn7bJ3ruyDsxt3DgMsAtHXpDx8D90D0qvmOpShsq57oQJtMO1Qrr0VaLFEvsnMkTScr3-Tmmb55GnsFptnDgwaJsgwGS07hVcob1lXVLf9q2UrQ'},
        #     {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wxpay.vid', 'path': '/', 'secure': False,
        #      'value': '1688850145931141'},
        #     {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wxpay.corpid', 'path': '/', 'secure': False,
        #      'value': '1970324963443594'},
        #     {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wwrtx.d2st', 'path': '/', 'secure': False,
        #      'value': 'a5538072'},
        #     {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.sid', 'path': '/', 'secure': False,
        #      'value': 'RTyw3gv73HNeWu1vNC8I_OewH8D9pNVER2emOPj91OKiHY3mZx8y0oAre6fDSIZy'},
        #     {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.ltype', 'path': '/', 'secure': False,
        #      'value': '1'}, {'domain': '.work.weixin.qq.com', 'expiry': 1648690020, 'httpOnly': False,
        #                      'name': 'Hm_lvt_9364e629af24cb52acc78b43e8c9f77d', 'path': '/', 'secure': False,
        #                      'value': '1617086828,1617093726,1617097791,1617154020'},
        #     {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.ref', 'path': '/', 'secure': False,
        #      'value': 'direct'},
        #     {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'Hm_lpvt_9364e629af24cb52acc78b43e8c9f77d',
        #      'path': '/', 'secure': False, 'value': '1617154020'},
        #     {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.refid', 'path': '/', 'secure': False,
        #      'value': '26611713121620184'},
        #     {'domain': '.qq.com', 'expiry': 1617240433, 'httpOnly': False, 'name': '_gid', 'path': '/', 'secure': False,
        #      'value': 'GA1.2.729688091.1617086828'},
        #     {'domain': 'work.weixin.qq.com', 'expiry': 1617185050, 'httpOnly': True, 'name': 'ww_rtkey', 'path': '/',
        #      'secure': False, 'value': '56kmueb'},
        #     {'domain': '.qq.com', 'expiry': 1680226033, 'httpOnly': False, 'name': '_ga', 'path': '/', 'secure': False,
        #      'value': 'GA1.2.1805803985.1617086828'},
        #     {'domain': '.work.weixin.qq.com', 'expiry': 1648622815, 'httpOnly': False, 'name': 'wwrtx.c_gdpr',
        #      'path': '/', 'secure': False, 'value': '0'},
        #     {'domain': '.work.weixin.qq.com', 'expiry': 1619746036, 'httpOnly': False, 'name': 'wwrtx.i18n_lan',
        #      'path': '/', 'secure': False, 'value': 'cht'}]
        #
        # db["cookies"]=cookies
        # db.close()#使用完需要关闭数据库连接，释放资源

        # cookies 的使用
        cookies = db["cookies"]  # 从数据库读取

        for cookie in cookies:
            if "expiry" in cookie.keys():
                cookie.pop("expiry")
            self.driver.add_cookie(cookie)

        self.driver.get("https://work.weixin.qq.com/wework_admin/frame")
        self.driver.find_element(By.ID, "menu_contacts").click()
